### ISSUE TITLE
No color when using lowercases

### ISSUE THREAD

**Issue by 444thLiao** [sanderlab/alignmentviewer#60]
It just a minor issue that has been described in the title.

When I upload a DNA alignment with the lowercases alphabet, neither color schemes were applied. 
If I changed it to uppercases, it will work.

**Comment by rocreguant** [comment]
Yes, that's done on purpose following the convention.
More info: https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Web&PAGE_TYPE=BlastDocs&DOC_TYPE=FAQ#lowercase
